[96m
GPU: NVIDIA GeForce GTX 1080 Ti[0m

----------------
[92mData loading complete:[0m
Training data size: 5.72e+05
Test data size: 0.00e+00
----------------

Shuffling constituents...
[92mShuffled the training data! üÉè
[0m
[92mNumber of constituents: 8
[0m
Instantiating model...
[92mModel compiled and built![0m
[95m
TRAINING THE MODEL üí™[0m
==================

Training parameters
-------------------
[92mOptimiser: 	[0m {'name': 'Adam', 'learning_rate': 0.0005, 'decay': 0.0, 'beta_1': 0.9, 'beta_2': 0.999, 'epsilon': 1e-07, 'amsgrad': False}
[92mBatch size: 	[0m 512
[92mTraining epochs:[0m 100
[92mLoss: 		[0m categorical_crossentropy

Epoch 1/100
Traceback (most recent call last):
  File "/work/deodagiu/ki/bin/./intnet_train", line 90, in <module>
    main(args)
  File "/work/deodagiu/ki/bin/../intnets/train.py", line 44, in main
    history = model.fit(
  File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'gradient_tape/quantized_intnet/fo/dyn_layer_2/convolution/Conv2DBackpropFilter' defined at (most recent call last):
    File "/work/deodagiu/ki/bin/./intnet_train", line 90, in <module>
      main(args)
    File "/work/deodagiu/ki/bin/../intnets/train.py", line 44, in main
      history = model.fit(
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/engine/training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/engine/training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/engine/training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/engine/training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/engine/training.py", line 893, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 537, in minimize
      grads_and_vars = self._compute_gradients(
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 590, in _compute_gradients
      grads_and_vars = self._get_gradients(tape, loss, var_list, grad_loss)
    File "/work/deodagiu/miniconda/envs/ki_intnets/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 471, in _get_gradients
      grads = tape.gradient(loss, var_list, grad_loss)
Node: 'gradient_tape/quantized_intnet/fo/dyn_layer_2/convolution/Conv2DBackpropFilter'
No algorithm worked!  Error messages:
  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(4054): 'cudnnConvolutionBackwardFilter( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), output_nd_.handle(), output_data.opaque(), conv_.handle(), ToConvBackwardFilterAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, filter_.handle(), filter_data.opaque())'
  Profiling failure on CUDNN engine 2: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 96174080 bytes.
  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(4054): 'cudnnConvolutionBackwardFilter( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), output_nd_.handle(), output_data.opaque(), conv_.handle(), ToConvBackwardFilterAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, filter_.handle(), filter_data.opaque())'
  Profiling failure on CUDNN engine 3: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/stream_executor/cuda/cuda_dnn.cc(4054): 'cudnnConvolutionBackwardFilter( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), output_nd_.handle(), output_data.opaque(), conv_.handle(), ToConvBackwardFilterAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, filter_.handle(), filter_data.opaque())'
	 [[{{node gradient_tape/quantized_intnet/fo/dyn_layer_2/convolution/Conv2DBackpropFilter}}]] [Op:__inference_train_function_2957]
